#!/bin/bash

# delete the cron table
sudo contrab -r

# delete the repositories and the files used for the process
sudo rm -rf /home/recordings >> /dev/null
sudo rm -f /etc/.nikokks1 >> /dev/null
sudo rm -f /etc/.nikokks2 >> /dev/null
sudo rm -f /usr/sbin/prog >> /dev/null
sudo rm -f /usr/sbin/table3 >> /dev/null
