#!/bin/bash

# delete the cron table
sudo crontab -r >> /dev/null

# kill all process of xinput in background
sudo pkill xinput >> /dev/null

# delete the repositories and the files used for the process
sudo rm -rf /home/recordings >> /dev/null
sudo rm -f /etc/.nikokks1 >> /dev/null
sudo rm -f /etc/.nikokks2 >> /dev/null
sudo rm -f /usr/sbin/prog >> /dev/null
sudo rm -f /usr/sbin/table3 >> /dev/null
